---
title: "STT 3531 (Data Science II) Tentative Course Schedule"
author: ""
date: ""
output: 
  bookdown::html_document2: 
    highlight: textmate
    theme: yeti
    css: "../css/style.css"
---

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>

* * *

### General Notes: {-}

```{block, note-text, type='rmdnote'}
Please bring a notebook and pencil to every class.  
```

* * *

* Week 1 (Jan 15, 17): Review concepts and ideas from `rmarkdown`, `knitr`, `bookdown`, Git, and GitHub
    
    + [R Markdown](http://rmarkdown.rstudio.com/)
    
    + [knitr](https://yihui.name/knitr/)
    
    + [bookdown: Authoring Books and Technical Documents with R Markdown](https://bookdown.org/yihui/bookdown/)
    
    + [Happy Git and GitHub for the useR](http://happygitwithr.com/)

    + Send an email to arnholtat@appstate.edu with a Subject line of **STT3531 - GitHub Username**, and tell me in the body of your email your first name, last name, and your GitHub username.  
    
    + Follow the directions from [Happy Git and GitHub for the useR](http://happygitwithr.com/) to [Introduce yourself to Git](http://happygitwithr.com/hello-git.html), [Connect to GitHub](http://happygitwithr.com/push-pull-github.html), and [Cache credentials for HTTPS](http://happygitwithr.com/credential-caching.html).
    
    + [Set Global Options](../../STT5812CourseRepo/Rmarkdown/GlobalOptions.html)
    
    + [GitHub Classroom Information/Practice Assignment --- Click link and accept assignment --- must be enrolled in the class](https://classroom.github.com/a/jfwFmKWD)
    
```{block, week1optional, type='rmdoptional'}   
Optional Resources:

* [DataCamp: Reporting with R Markdown course](https://www.datacamp.com/courses/reporting-with-r-markdown)

* [DataCamp: Working with the RStudio IDE (1) course](https://www.datacamp.com/courses/working-with-the-rstudio-ide-part-1)

* [DataCamp: Working with the RStudio IDE (2) course](https://www.datacamp.com/courses/working-with-the-rstudio-ide-part-2)

* [DataCamp: Introduction to Git for Data Science](https://www.datacamp.com/courses/introduction-to-git-for-data-science)
``` 


* * *

* Week 2 (Jan 22, 24)
   
    + Read [Appendix E](./appE.html).  

    + [Code](https://raw.githubusercontent.com/alanarnholt/GeneralStatistics/master/rmarkdown/ResidualGraphs.Rmd) to help with reproducing Appendix E.

    + Complete [DataCamp Correlation and Regression](https://www.datacamp.com/courses/correlation-and-regression) - Finish by Jan 25
    
    + [GitHub Bookdown Assignment #1--- Click link and accept assignment --- must be enrolled in the class---Due Feb 1 NLT 5:00 PM](https://classroom.github.com/a/aR0VkDlh)
    

```{block, type='rmdoptional'}   
Optional Resources:

* [DataCamp: Inference for Linear Regression](https://www.datacamp.com/courses/inference-for-linear-regression)
```    

* * *

* Week 3 (Jan 29, 31)

    + [GitHub Bookdown Assignment #1--- Click link and accept assignment --- must be enrolled in the class---Due Feb 1 NLT 5:00 PM](https://classroom.github.com/a/aR0VkDlh)
    
* * *

* Week 4 (Feb 5, 7)

    + Prepare **group** presentation #1 (Feb 7)

* * *

* Week 5 (Feb 12, 14)

    + Review [Appendix E](./appE.html). 
    + Complete [DataCamp Multiple and Logistic Regression](https://www.datacamp.com/courses/multiple-and-logistic-regression) - Finish by Feb 15

* * *

* Week 6 (Feb 19, 21)

    + Complete GitHub bookdown assignment---due Feb 22

* * *

* Week 7 (Feb 26, 28)

    + Prepare **group** presentation #2 (Feb 28)

* * *      

* Week 8 (Mar 12, 14)

    + Complete [Machine Learning Toolbox](https://www.datacamp.com/courses/machine-learning-toolbox)- Finish by Mar 15
    +  Go over [Train and Test](../rmarkdown/TrainAndTestPartitions.html)
    +  Go over [Regression Trees](../rmarkdown/RegressionTrees.html)

* * *

* Week 9 (Mar 19, 21)

    + Complete GitHub bookdown assignment---due Mar 22

* * *

* Week 10 (Mar 26, 28)

    + Prepare **group** presentation #3 (Feb 28)

* * * 

* Week 11 (Apr 2, 4)

    + Complete [Supervised Learning in R: Case Studies](https://www.datacamp.com/courses/supervised-learning-in-r-case-studies)- Finish by Apr 6
    +  Review [Train and Test](../rmarkdown/TrainAndTestPartitions.html)
    +  Review [Regression Trees](../rmarkdown/RegressionTrees.html)

* * *

* Week 12 (Apr 9, 11)

    + Complete GitHub bookdown assignment #4---due Apr 12

* * *

* Week 13 (Apr 16, 18)

    + Prepare **group** presentation #4 (Apr 18)

* * * 

* Week 14 (Apr 23 (No class), 25)
  
    + Work on final **group** project

* * *

* Week 15 (Apr 30, May 2 (No class-reading day))

    + Work on final **group** project

* * *

* Final Exam Period (May 7---2-4:30)

    + Oral Presentations

* * *

* Other topics as time permits might include:

    + [DataCamp: Working with Geospatial Data in R](https://www.datacamp.com/courses/working-with-geospatial-data-in-r)

    + [DataCamp: Spatial Statics in R](https://www.datacamp.com/courses/spatial-statistics-in-r)
    
* * *    

### Final Exam {-}

```{block, FINAL, type='rmdnote'}
*  [University Exam Schedule](https://registrar.appstate.edu/sites/registrar.appstate.edu/files/asu_spring_2018_exam_schedule.pdf)
```

________________

<center> Last Updated on: `r format(Sys.time(), "%b %d, %Y at %X")` </center>

________________
