---
title: "STT 3860 - Introduction to Statistical Modeling - Tentative Course Schedule - Spring 2026"
author: ""
date: ""
output: 
  bookdown::html_document2:
    axe: 
    highlight: textmate
    theme: yeti
    css: "../css/style.css"
---

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>

* * *

## General Notes: {-}

```{block, note-text, type='rmdnote'}
+ Please bring a notebook and pencil to every class.

+ [QUARTO cheat sheet](https://images.datacamp.com/image/upload/v1676540721/Marketing/Blog/Quarto_Cheat_Sheet.pdf)
```

* * *

## Week 1: (Jan 13 & 15) {-}
    
+ Before the first class meeting, read Chapter 1 [Why Git? Why GitHub?](https://happygitwithr.com/big-picture) from [_Happy Git and GitHub for the useR_](https://happygitwithr.com/).

+ Read chapter 1 - [Software for modeling](https://www.tmwr.org/software-modeling) from [_Tidy Modeling with `R`_](https://www.tmwr.org/).
    
+ Read as needed [Happy Git and GitHub for the useR](http://happygitwithr.com/)

+ [Start Chapters 1 and 2 in _Introduction to Statistics in R_ on DataCamp](https://app.datacamp.com/groups/stt3850-s2025/assignments)---Due Jan 19 NLT 5:00 PM 
    
+ Sign-up for a free account on [GitHub](https://github.com).  When you register for a free individual GitHub account, request a [student discount](https://education.github.com) to obtain a few private repositories as well as unlimited public repositories.  Please use something similar to **FirstNameLastName** as your username when you register with GitHub.  For example, my username on GitHub is *alanarnholt*. If you have a popular name such as John Smith, you may need to provide some other distinguishing characteristic in your username.  

+ Send an email to arnholtat@appstate.edu with a Subject line of **STT3860 - GitHub Username**, and tell me in the body of your email your first name, last name, and your GitHub username.  
    
+ Make sure RStudio is set up to communicate with Git by following the directions in [HappyGitWithR](https://happygitwithr.com/hello-git.html) for introducing yourself to Git.
    
+ Cache your credentials and set up a personal access token (PAT) by following the directions in [HappyGitWithR](https://happygitwithr.com/https-pat).
  
+ TL;DR the chapters in Happy Git With R — follow this document to [Set up Git and GitHub](../handouts/setup.html)
  
+ [VIDEO of the setup process](https://drive.google.com/file/d/1L-v9qAVHWtvXOTYjY8wvedH5VyzmeQeL/view)
  
+ [Video of how to accept and clone assignments (video is for my STT 3850 class; but, the process will be the same for this class)](https://drive.google.com/file/d/1JUag-0U-reD_JcKHvez50I_4R-CCMUMt/view)

+ [Set Global Options](https://stat-ata-asu.github.io/STT5812CourseRepo/Rmarkdown/GlobalOptions.html)
    


    
```{block, week1optional, type='rmdoptional'}   
Optional Resources:

* [Miscellaneous RMarkdown Tips](https://alanarnholt.github.io/GeneralStatistics/rmarkdown/MiscRmarkdown.html)

* [DataCamp: Communicating with Data in the Tidyverse](https://www.datacamp.com/courses/communicating-with-data-in-the-tidyverse)

* [Data Science with R](https://stat-ata-asu.github.io/R_DS_BD2020/)

* [DataCamp: Introduction to Git for Data Science](https://www.datacamp.com/courses/introduction-to-git-for-data-science)

* [Reading in Data](https://alanarnholt.github.io/STT3850/Handouts/WorkingWithDataRevised.html)
``` 


* * *

## Week 2: (Jan 20 & 22) {-}

+ Read the chapter 2 - [A Tidyverse Primer](https://www.tmwr.org/tidyverse) from [_Tidy Modeling with `R`_](https://www.tmwr.org/).

+ [Tidyverse Primer Notes](../QuartoStuff/tidyverse_primer.html)

+ [Start Chapters 3 and 4 in _Introduction to Statistics in R_ on DataCamp](https://app.datacamp.com/groups/stt3850-s2025/assignments)---Due Jan 23 NLT 5:00 PM 
  
 
* * * 

## Week 3: (Jan 27 & 29) {-}
   
+ Read chapter 3 - [A Review of R Modeling Fundamentals](https://www.tmwr.org/base-r) from [_Tidy Modeling with `R`_](https://www.tmwr.org/). 

+ [Review of R Modeling Notes](../QuartoStuff/TMWRCHAP3.html)

+ Start reproduction of [_Introduction to Statistics in R_](https://classroom.github.com/a/jm6UNAaf)---Due Feb 2 NLT 5:00 PM
    
* * *

## Week 4: (Feb 3 & 5) {-}

+ Finish reproduction of [_Introduction to Statistics in R_](https://classroom.github.com/a/jm6UNAaf)---Due Feb 2 NLT 5:00 PM

+ Read chapter 4 - [The Ames Housing Data](https://www.tmwr.org/ames) from [_Tidy Modeling with `R`_](https://www.tmwr.org/). 

+ Read Chapters 1-5 of [Correlation and Regression](https://mathr.appstate.edu/connect/content/d219d887-2f38-428f-baed-16575e6770c5)

+ [Start Chapters 1 and 2 in _Modeling with Data in the Tidyverse_ on DataCamp](https://app.datacamp.com/groups/stt3850-s2025/assignments)---Due Feb 6 NLT 5:00 PM 
    

* * *

## Week 5: (Feb 10 & 12) {-}

+ Read chapter 5 - [Spending our Data](https://www.tmwr.org/splitting) from [_Tidy Modeling with `R`_](https://www.tmwr.org/). 

+ [Start Chapters 3 and 4 in _Modeling with Data in the Tidyverse_ on DataCamp](https://app.datacamp.com/groups/stt3850-s2025/assignments)---Due Feb 13 NLT 5:00 PM 

+ Misc Regression [topics](https://alanarnholt.github.io/STT3850/Rmarkdown/MiscRegression.html)
    
  
* * *

## Week 6: (Feb 17 & 19) {-}

+ Read chapter 6 - [Fitting Models with parsnip](https://www.tmwr.org/models) from [_Tidy Modeling with `R`_](https://www.tmwr.org/)

+ Read [Appendix E.](https://mdsr-book.github.io/mdsr2e/ch-regression.html#simple-linear-regression)

+ Start reproduction of [_Modeling with Data in the Tidyverse_](https://classroom.github.com/a/iF-wbdB9)---Due Feb 23 NLT 5:00 PM

+ In class review [this document.](https://alanarnholt.github.io/STT3850/Handouts/RegHandout.html)
  



* * *

## Week 7: (Feb 24 & 26) {-}

+ Finish reproduction of [_Modeling with Data in the Tidyverse_](https://classroom.github.com/a/iF-wbdB9)---Due Feb 23 NLT 5:00 PM

+ Read chapter 7 - [A Model Workflow](https://www.tmwr.org/workflows) from [_Tidy Modeling with `R`_](https://www.tmwr.org/)

+ Read [Multiple and Logistic Regression](https://mathr.appstate.edu/connect/content/808fcaf7-161a-481d-acec-20f5114e1537)

+ [Start Chapters 1 and 2 in _Modeling with Tidymodels in R_ on DataCamp](https://app.datacamp.com/groups/stt3850-s2025/assignments)---Due Feb 27 NLT 5:00 PM 

+ Read [Not `mtcars` AGAIN](../QuartoStuff/Not_mtcars_AGAIN.html)
    
* * *

## Week 8: (Mar 3 & 5) {-}

+ Read chapter 8 - [Feature Engineering with recipes](https://www.tmwr.org/recipes) from [_Tidy Modeling with `R`_](https://www.tmwr.org/)

+ Read [Build a model](../QuartoStuff/Build_A_Model.html) and [Preprocess your data with recipes](../QuartoStuff/Preprocess_your_data_with_recipes.html)
    
+ [Start Chapters 3 and 4 in _Modeling with Tidymodels in R_ on DataCamp](https://app.datacamp.com/groups/stt3850-s2025/assignments)---Due Mar 6 NLT 5:00 PM 

+ Start reproduction of [_Modeling with Tidymodels in R_](https://classroom.github.com/a/4i3ONvjK) - Due Mar 19 NLT 5:00 PM
  

* * *   

## Spring Break: Mar 9---13 {-}

* * *

## Week 9: (Mar 17 & 19) {-}

+ Read chapter 9 - [Judging Model Effectiveness](https://www.tmwr.org/performance) from [_Tidy Modeling with `R`_](https://www.tmwr.org/)

+ Work on reproduction of [_Modeling with Tidymodels in R_](https://classroom.github.com/a/4i3ONvjK) - Due Mar 19 NLT 5:00 PM

+ Directions for [Project 1](../QuartoStuff/Project_1_Regression.html)

+ Accept [Project 1](https://classroom.github.com/a/1ARryzVK) - Presentations will be March 31. 
    
* * *

## Week 10: (Mar 24 & 26) {-}

+ Read chapter 10 - [Resampling for Evaluating Performance](https://www.tmwr.org/resampling) from [_Tidy Modeling with `R`_](https://www.tmwr.org/)

+ Work on [Project 1](https://classroom.github.com/a/1ARryzVK) - Presentations will be March 31.

* * *


## Week 11: (Mar 31 & Apr 2) {-}

+ Group presentations for [Project 1](https://classroom.github.com/a/1ARryzVK)---Mar 31

+ Read chapter 11 [Comparing Models with Resampling](https://www.tmwr.org/compare) from [_Tidy Modeling with `R`_](https://www.tmwr.org/)

+ Read [Tree Based Methods](../QuartoStuff/Tree_Based_Methods.html)

+ Read Chapters 2-4 in [Tree based Models in R](https://mathr.appstate.edu/connect/content/417890f7-c144-44ec-86b5-6437891c8c2d)
    
+ [Start Chapters 1 and 2 in _Machine Learning with Tree Based Models in R_ on DataCamp](https://app.datacamp.com/groups/stt3850-s2025/assignments)---Due Apr 6 NLT 5:00 PM 

```{block, week11optional, type='rmdoptional'}   
Optional Resources:

+ Review as needed [Train and Test](../rmarkdown/TrainAndTestPartitions.html)
    
+ Review as needed [Regression Trees](../rmarkdown/RegressionTrees.html)
    
+ Review as needed [Predictive Model Building](https://stat-ata-asu.github.io/PredictiveModelBuilding/)
```
  
* * * 

## Week 12: (Apr 7 & 9) {-}

+ Read chapter 12 - [Model Tuning and the Dangers of Overfitting](https://www.tmwr.org/tuning) from [_Tidy Modeling with `R`_](https://www.tmwr.org/)
    
+ Read Chapters 5-6 in [Tree based Models in R](https://mathr.appstate.edu/connect/content/417890f7-c144-44ec-86b5-6437891c8c2d)

+ [Start Chapters 3 and 4 in _Machine Learning with Tree Based Models in R_ on DataCamp](https://app.datacamp.com/groups/stt3850-s2025/assignments)---Due Apr 13 NLT 5:00 PM 

+ Start reproduction of [_Machine Learning with Tree Based Models in R_](https://classroom.github.com/a/n-LskGWs)---Due Apr 20 NLT 5:00 PM

```{block, week12optional, type='rmdoptional'}   
Optional Resources:

+ Review as needed [Train and Test](../rmarkdown/TrainAndTestPartitions.html)
    
+ Review as needed [Regression Trees](../rmarkdown/RegressionTrees.html)
    
+ Review as needed [Predictive Model Building](https://stat-ata-asu.github.io/PredictiveModelBuilding/)
```


    
* * *

## Week 13: (Apr 14 & 16) {-}

+ Read chapter 13 - [Grid Search](https://www.tmwr.org/grid-search) from [_Tidy Modeling with `R`_](https://www.tmwr.org/)

+ Work on reproduction of [_Machine Learning with Tree Based Models in R_](https://classroom.github.com/a/n-LskGWs)---Due Apr 20 NLT 5:00 PM

+ Read [Stack Overflow](../QuartoStuff/Stack_Overflow.html)

+ Read [VOTERS](../QuartoStuff/VOTERS.html) 

+ Read [What do nuns think?](../QuartoStuff/nuns.html) 
    
* * *

## Week 14: (Apr 21 & 23) {-}

+ Finish reproduction of [_Machine Learning with Tree Based Models in R_](https://classroom.github.com/a/n-LskGWs) - Due Apr 20 NLT 5:00 PM

+ Directions for [Project 2](../QuartoStuff/Project_2_Classification.html)

+ Accept [Project 2](https://classroom.github.com/a/rKPxHeQF) ---Group presentations will be May 7 during the final exam period (8 am---10:30 am).    
  
* * * 

## Week 15: (Apr 28) {-}

+ Work on Project 2.

* * *


## Final Exam Period (May 7, 8 am---10:30 am) {-}

+ Final Group Presentations for Project 2
  
* * *


### Final Exam {-}

```{block, FINAL, type='rmdnote'}
*  [University Exam Schedule](https://registrar.appstate.edu/sites/default/files/spring_2026_exam_schedule.pdf)
```

________________

<center> Last Updated on: `r format(Sys.time(), "%b %d, %Y at %X")` </center>

________________
