---
title: "STT 3860 - Introduction to Statistical Modeling - Tentative Course Schedule - Spring 2024"
author: ""
date: ""
output: 
  bookdown::html_document2: 
    highlight: textmate
    theme: yeti
    css: "../css/style.css"
---

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>

* * *

## General Notes: {-}

```{block, note-text, type='rmdnote'}
+ Please bring a notebook and pencil to every class.

+ [QUARTO cheat sheet](https://images.datacamp.com/image/upload/v1676540721/Marketing/Blog/Quarto_Cheat_Sheet.pdf)
```

* * *

## Week 1: (Jan 16 -- 18) {-}
    
+ Before the first class meeting, read Chapter 1 [Why Git? Why GitHub?](https://happygitwithr.com/big-picture) of Happy Git With `R`.

+ [R Markdown](http://rmarkdown.rstudio.com/)
    
+ [knitr](https://yihui.name/knitr/)
    
+ [bookdown: Authoring Books and Technical Documents with R Markdown](https://bookdown.org/yihui/bookdown/)
    
+ [Happy Git and GitHub for the useR](http://happygitwithr.com/)
    
+ Sign-up for a free account on [GitHub](https://github.com).  When you register for a free individual GitHub account, request a [student discount](https://education.github.com) to obtain a few private repositories as well as unlimited public repositories.  Please use something similar to **FirstNameLastName** as your username when you register with GitHub.  For example, my username on GitHub is *alanarnholt*. If you have a popular name such as John Smith, you may need to provide some other distinguishing characteristic in your username.  

+ Send an email to arnholtat@appstate.edu with a Subject line of **STT3860 - GitHub Username**, and tell me in the body of your email your first name, last name, and your GitHub username.  
    
+ Make sure RStudio is set up to communicate with Git by following the directions in [HappyGitWithR](https://happygitwithr.com/hello-git.html) for introducing yourself to Git.
    
+ Set cache your credentials and set up a personal access token (PAT) by following the directions in [HappyGitWithR](https://happygitwithr.com/credential-caching.html).
  
+ TL;DR the chapters in Happy Git With R — follow this document to [Set up Git and GitHub](../handouts/setup.html)
  
+ [VIDEO of the setup process](https://drive.google.com/file/d/1L-v9qAVHWtvXOTYjY8wvedH5VyzmeQeL/view)
  
+ [Video of how to accept and clone assignments (video is for my STT 3850 class; but, the process will be the same for this class)](https://drive.google.com/file/d/1JUag-0U-reD_JcKHvez50I_4R-CCMUMt/view)

+ [Set Global Options](https://stat-ata-asu.github.io/STT5812CourseRepo/Rmarkdown/GlobalOptions.html)
    
+ [Miscellaneous Tips](https://alanarnholt.github.io/GeneralStatistics/rmarkdown/MiscRmarkdown.html)

+ [Start Chapters 1 and 2 in Inference for Numerical Data in R on DataCamp](https://app.datacamp.com/groups/stt3860-sp24/assignments)---Due Jan 23 NLT 5:00 PM 
    
```{block, week1optional, type='rmdoptional'}   
Optional Resources:

* [DataCamp: Communicating with Data in the Tidyverse](https://www.datacamp.com/courses/communicating-with-data-in-the-tidyverse)

* [Data Science with R](https://stat-ata-asu.github.io/R_DS_BD2020/)

* [DataCamp: Introduction to Git for Data Science](https://www.datacamp.com/courses/introduction-to-git-for-data-science)

* [Reading in Data](https://alanarnholt.github.io/STT3850/Handouts/WorkingWithDataRevised.html)
``` 


* * *

## Week 2: (Jan 23 -- 25) {-}

+ [Complete Chapters 1 and 2 in Inference for Numerical Data in R on DataCamp](https://app.datacamp.com/groups/stt3860-sp24/assignments)---Due Jan 23 NLT 5:00 PM 

+ [Complete Chapters 3 and 4 in Inference for Numerical Data in R on DataCamp](https://app.datacamp.com/groups/stt3860-sp24/assignments)---Due Jan 24 NLT 5:00 PM 
  
+ Complete and turn in a hard copy of your [quick sheet of "Inference for Numerical Data in R"](https://classroom.github.com/a/XCfpFLV8) using Quarto---Due Jan 25 NLT 5:00 PM 
  
+ [START LAB1: Questioning and Cleaning the bodyfat data Lab---Due Feb 1 NLT 5:00 PM](https://classroom.github.com/a/MNDYBrLm) 
  
 
* * * 

## Week 3: (Jan 30 -- Feb 1) {-}
   
+ [Complete LAB1: Questioning and Cleaning the bodyfat data Lab---Due Feb 1 NLT 5:00 PM](https://classroom.github.com/a/MNDYBrLm)        
    
* * *

## Week 4: (Feb 6 -- 8) {-}

+ Read Chapters 1-5 of [Correlation and Regression](https://mathr.appstate.edu/connect/content/d219d887-2f38-428f-baed-16575e6770c5)
    
+ Misc Regression [topics](https://alanarnholt.github.io/STT3850/Rmarkdown/MiscRegression.html)
  
+ Complete and turn in a hard copy of your [quick sheet of "Correlation and Regression"](https://classroom.github.com/a/WeJznz-_) using Quarto---Due Feb 8 NLT 5:00 PM   
    
* * *

## Week 5: (Feb 13 -- 15) {-}

+ [Complete Chapters 1-4 in Modeling with Data in the Tidyverse on DataCamp](https://app.datacamp.com/groups/stt3860-sp24/assignments)---Due Feb 14 NLT 5:00 PM

+ Misc Regression [topics](https://alanarnholt.github.io/STT3850/Rmarkdown/MiscRegression.html)
    
 + Complete and turn in a hard copy of your [quick sheet of "Modeling with Data in the Tidyverse"](https://classroom.github.com/a/QVsh7huA) using Quarto---Due Feb 15 NLT 5:00 PM
  
* * *

## Week 6: (Feb 20 -- 22) {-}

+ In class review [this document.](https://alanarnholt.github.io/STT3850/Handouts/RegHandout.html)
   
+ Pick a data set from the [UCI machine learning repository](https://archive.ics.uci.edu/ml/index.php) where you can use linear regression to create a model after cleaning the data as appropriate.

+ Data set clean up due NLT 5:00 PM Feb 22 for [Group Presentation # 1](https://classroom.github.com/a/q_Xx6jBT)


* * *

## Week 7: (Feb 27 -- 29) {-}

+ First group presentations Feb 29    
    
* * *

## Week 8: (Mar 5 -- 7) {-}

+ Read [Appendix E.](https://mdsr-book.github.io/mdsr2e/ch-regression.html#simple-linear-regression)

+ Read [Predictive Model Building](https://stat-ata-asu.github.io/PredictiveModelBuilding/)
    
+ Read [Multiple and Logistic Regression](https://mathr.math.appstate.edu/connect/content/493bca23-1118-4e56-9e3f-f35585deb611)

+ [Cross Validation Handout](https://stat-ata-asu.github.io/STT3851ClassRepo/Rmarkdown/Cross-ValidationInClassHO.html)
    
+ [Cross Validation starter code](https://classroom.github.com/a/-yy9rCLk)

+ [Complete Chapters  1-5 in Machine Learning with `caret` in R on DataCamp](https://app.datacamp.com/groups/stt3860-sp24/assignments)---Due Mar 6 NLT 5:00 PM 
  
+ Complete and turn in a hard copy of your [quick sheet of "Machine Learning with `caret` in R"](https://classroom.github.com/a/vf-ZhJz_) using Quarto---Due Mar 7 NLT 5:00 PM 
    
    
* * *   

## Spring Break: Mar 11 -- 15 {-}

* * *

## Week 9: (Mar 19 -- 21) {-}

+ Read [Predictive Model Building](https://stat-ata-asu.github.io/PredictiveModelBuilding/)
    
+ Read [Multiple and Logistic Regression](https://mathr.math.appstate.edu/connect/content/493bca23-1118-4e56-9e3f-f35585deb611)

+ [START LAB2: Linear models with the bodyfat data Lab---Due Mar 28 NLT 5:00 PM](https://classroom.github.com/a/9FVQcAzL) 
    
    
* * *

## Week 10: (Mar 26 -- 28) {-}


+ [Complete LAB2: Linear models with the bodyfat data Lab---Due Mar 28 NLT 5:00 PM](https://classroom.github.com/a/9FVQcAzL) 

+ Pick a data set from the [UCI machine learning repository](https://archive.ics.uci.edu/ml/index.php) where you can use logistic linear regression to create a model after cleaning the data as appropriate.

+ Data set clean up due NLT 5:00 PM Mar 28 for [Group Presentation # 2](https://classroom.github.com/a/1cTwwkC2)

* * *


## Week 11: (Apr 2 -- 4) {-}

+ Second group presentations Apr 4
  
* * * 

## Week 12: (Apr 9 -- 11) {-}

+ Read [Tree based Models in R](https://mathr.appstate.edu/connect/content/417890f7-c144-44ec-86b5-6437891c8c2d)
    
+ Review as needed [Train and Test](../rmarkdown/TrainAndTestPartitions.html)
    
+ Review as needed [Regression Trees](../rmarkdown/RegressionTrees.html)
    
+ Review as needed [Predictive Model Building](https://stat-ata-asu.github.io/PredictiveModelBuilding/)

+ Complete and turn in a hard copy of your [quick sheet of "Tree based Models in R"](https://classroom.github.com/a/giHyXM04) using Quarto---Due Apr 11 NLT 5:00 PM 
    
+ [START LAB3: Non-linear models with the bodyfat data Lab---Due Apr 18 NLT 5:00 PM](https://classroom.github.com/a/tou-HMiV) 
    
* * *

## Week 13: (Apr 16 -- 18) {-}

+ [Complete LAB3: Non-linear models with the bodyfat data Lab---Due Apr 18 NLT 5:00 PM](https://classroom.github.com/a/tou-HMiV) 

+ Pick a data set from the [UCI machine learning repository](https://archive.ics.uci.edu/ml/index.php) where you can create a model using trees.  

+ Clean chosen data and make models
    
* * *

## Week 14: (Apr 23 -- 25) {-}

+ Clean chosen data and make models
  
    
  
* * * 

## Week 15: (Apr 30 -- May 1) {-}

+ Clean chosen data and make models

+ Prepare **group** presentation.  Accept materials [here](https://classroom.github.com/a/1Tsgp4Nz) 

* * *


## Final Exam Period (May 11---11 am -1:30 pm) {-}

+ Final Group Presentations
  
* * *


### Final Exam {-}

```{block, FINAL, type='rmdnote'}
*  [University Exam Schedule](https://registrar.appstate.edu/sites/default/files/app_state_spring_2024_exam_schedule_final.pdf)
```

________________

<center> Last Updated on: `r format(Sys.time(), "%b %d, %Y at %X")` </center>

________________
