---
title: "STT 3860 - Introduction to Statistical Modeling - Tentative Course Schedule - Spring 2025"
author: ""
date: ""
output: 
  bookdown::html_document2: 
    highlight: textmate
    theme: yeti
    css: "../css/style.css"
---

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>

* * *

## General Notes: {-}

```{block, note-text, type='rmdnote'}
+ Please bring a notebook and pencil to every class.

+ [QUARTO cheat sheet](https://images.datacamp.com/image/upload/v1676540721/Marketing/Blog/Quarto_Cheat_Sheet.pdf)
```

* * *

## Week 1: (Jan 14 & 16) {-}
    
+ Before the first class meeting, read Chapter 1 [Why Git? Why GitHub?](https://happygitwithr.com/big-picture) of Happy Git With `R`.

+ Read the chapter [Software for modeling](https://www.tmwr.org/software-modeling).
    
+ Read as needed [Happy Git and GitHub for the useR](http://happygitwithr.com/)

+ [Start Chapters 1 and 2 in _Introduction to Statistics in R_ on DataCamp](https://app.datacamp.com/groups/stt3850-s2025/assignments)---Due Jan 20 NLT 5:00 PM 
    
+ Sign-up for a free account on [GitHub](https://github.com).  When you register for a free individual GitHub account, request a [student discount](https://education.github.com) to obtain a few private repositories as well as unlimited public repositories.  Please use something similar to **FirstNameLastName** as your username when you register with GitHub.  For example, my username on GitHub is *alanarnholt*. If you have a popular name such as John Smith, you may need to provide some other distinguishing characteristic in your username.  

+ Send an email to arnholtat@appstate.edu with a Subject line of **STT3860 - GitHub Username**, and tell me in the body of your email your first name, last name, and your GitHub username.  
    
+ Make sure RStudio is set up to communicate with Git by following the directions in [HappyGitWithR](https://happygitwithr.com/hello-git.html) for introducing yourself to Git.
    
+ Cache your credentials and set up a personal access token (PAT) by following the directions in [HappyGitWithR](https://happygitwithr.com/https-pat).
  
+ TL;DR the chapters in Happy Git With R — follow this document to [Set up Git and GitHub](../handouts/setup.html)
  
+ [VIDEO of the setup process](https://drive.google.com/file/d/1L-v9qAVHWtvXOTYjY8wvedH5VyzmeQeL/view)
  
+ [Video of how to accept and clone assignments (video is for my STT 3850 class; but, the process will be the same for this class)](https://drive.google.com/file/d/1JUag-0U-reD_JcKHvez50I_4R-CCMUMt/view)

+ [Set Global Options](https://stat-ata-asu.github.io/STT5812CourseRepo/Rmarkdown/GlobalOptions.html)
    


    
```{block, week1optional, type='rmdoptional'}   
Optional Resources:

* [Miscellaneous RMarkdown Tips](https://alanarnholt.github.io/GeneralStatistics/rmarkdown/MiscRmarkdown.html)

* [DataCamp: Communicating with Data in the Tidyverse](https://www.datacamp.com/courses/communicating-with-data-in-the-tidyverse)

* [Data Science with R](https://stat-ata-asu.github.io/R_DS_BD2020/)

* [DataCamp: Introduction to Git for Data Science](https://www.datacamp.com/courses/introduction-to-git-for-data-science)

* [Reading in Data](https://alanarnholt.github.io/STT3850/Handouts/WorkingWithDataRevised.html)
``` 


* * *

## Week 2: (Jan 21 & 23) {-}

+ Read the chapter [A Tidyverse Primer](https://www.tmwr.org/tidyverse).

+ [Tidyverse Primer Notes](../QuartoStuff/tidyverse_primer.html)

+ [Start Chapters 3 and 4 in _Introduction to Statistics in R_ on DataCamp](https://app.datacamp.com/groups/stt3850-s2025/assignments)---Due Jan 24 NLT 5:00 PM 
  
 
* * * 

## Week 3: (Jan 28 & 30) {-}
   
+ Read the chapter [A Review of R Modeling Fundamentals](https://www.tmwr.org/base-r). 

+ [Review of R Modeling Notes](../QuartoStuff/TMWRCHAP3.html)

+ Start reproduction of [_Introduction to Statistics in R_](https://classroom.github.com/a/jm6UNAaf) - Due Feb 3 NLT 5:00 PM
    
* * *

## Week 4: (Feb 4 & 6) {-}

+ Finish reproduction of [_Introduction to Statistics in R_](https://classroom.github.com/a/jm6UNAaf) - Due Feb 3 NLT 5:00 PM

+ Read the chapter [The Ames Housing Data](https://www.tmwr.org/ames). 

+ Read Chapters 1-5 of [Correlation and Regression](https://mathr.appstate.edu/connect/content/d219d887-2f38-428f-baed-16575e6770c5)

+ [Start Chapters 1 and 2 in _Modeling with Data in the Tidyverse_ on DataCamp](https://app.datacamp.com/groups/stt3850-s2025/assignments)---Due Feb 7 NLT 5:00 PM 
    

* * *

## Week 5: (Feb 11 & 13) {-}

+ Read the chapter [Spending our Data](https://www.tmwr.org/splitting). 

+ [Start Chapters 3 and 4 in _Modeling with Data in the Tidyverse_ on DataCamp](https://app.datacamp.com/groups/stt3850-s2025/assignments)---Due Feb 14 NLT 5:00 PM 

+ Misc Regression [topics](https://alanarnholt.github.io/STT3850/Rmarkdown/MiscRegression.html)
    
  
* * *

## Week 6: (Feb 18 & 20) {-}

+ Read the chapter [Fitting Models with parsnip](https://www.tmwr.org/models)

+ Read [Appendix E.](https://mdsr-book.github.io/mdsr2e/ch-regression.html#simple-linear-regression)

+ Start reproduction of [_Modeling with Data in the Tidyverse_](https://classroom.github.com/a/iF-wbdB9) - Due Feb 24 NLT 5:00 PM

+ In class review [this document.](https://alanarnholt.github.io/STT3850/Handouts/RegHandout.html)
  
+ [Tree Based Methods](../QuartoStuff/Tree_Based_Methods.html)


* * *

## Week 7: (Feb 25 & 27) {-}

+ Finish reproduction of [_Modeling with Data in the Tidyverse_](https://classroom.github.com/a/iF-wbdB9) - Due Feb 24 NLT 5:00 PM

+ Read the chapter [A Model Workflow](https://www.tmwr.org/workflows) 

+ Read [Multiple and Logistic Regression](https://mathr.appstate.edu/connect/content/808fcaf7-161a-481d-acec-20f5114e1537)

+ [Start Chapters 1 and 2 in _Modeling with Tidymodels in R_ on DataCamp](https://app.datacamp.com/groups/stt3850-s2025/assignments)---Due Feb 28 NLT 5:00 PM 

+ [Not `mtcars` AGAIN](../QuartoStuff/Not_mtcars_AGAIN.html)
    
* * *

## Week 8: (Mar 4 & 6) {-}

+ Read the chapter [Feature Engineering with recipes](https://www.tmwr.org/recipes)

+ Read [Predictive Model Building](https://stat-ata-asu.github.io/PredictiveModelBuilding/)
    
+ [Start Chapters 3 and 4 in _Modeling with Tidymodels in R_ on DataCamp](https://app.datacamp.com/groups/stt3850-s2025/assignments)---Due Mar 7 NLT 5:00 PM 

+ Start reproduction of [_Modeling with Tidymodels in R_](https://classroom.github.com/a/4i3ONvjK) - Due Mar 24 NLT 5:00 PM
    
+ [Stack Overflow](../QuartoStuff/Stack_Overflow.html)

* * *   

## Spring Break: Mar 10 -- 14 {-}

* * *

## Week 9: (Mar 18 & 20) {-}

+ Read the chapter [Judging Model Effectiveness](https://www.tmwr.org/performance)

+ Work on reproduction of [_Modeling with Tidymodels in R_](https://classroom.github.com/a/4i3ONvjK) - Due Mar 24 NLT 5:00 PM

+ [VOTERS](../QuartoStuff/VOTERS.html)    
    
* * *

## Week 10: (Mar 25 & 27) {-}

+ Finish reproduction of [_Modeling with Tidymodels in R_](https://classroom.github.com/a/4i3ONvjK) - Due Mar 24 NLT 5:00 PM

+ Read the chapter [Resampling for Evaluating Performance](https://www.tmwr.org/resampling)

+ [Cross Validation Handout](https://stat-ata-asu.github.io/STT3851ClassRepo/Rmarkdown/Cross-ValidationInClassHO.html)
    
+ [Cross Validation starter code]()

+ Pick data for group project #1 from `modeldata` package.  Data must have at least 8 variables and 1,000 or more rows.  Accept group project [here]().  Group presentations will be April 1.

+ [What do nuns think?](../QuartoStuff/nuns.html)  

* * *


## Week 11: (Apr 1 & 3) {-}

+ Group presentations for project #1 - Apr 1.

+ Read the chapter [Comparing Models with Resampling](https://www.tmwr.org/compare)

+ Read Chapters 2-4 in [Tree based Models in R](https://mathr.appstate.edu/connect/content/417890f7-c144-44ec-86b5-6437891c8c2d)
    
+ [Start Chapters 1 and 2 in _Machine Learning with Tree Based Models in R_ on DataCamp](https://app.datacamp.com/groups/stt3850-s2025/assignments)---Due Apr 7 NLT 5:00 PM 

+ Review as needed [Train and Test](../rmarkdown/TrainAndTestPartitions.html)
    
+ Review as needed [Regression Trees](../rmarkdown/RegressionTrees.html)
    
+ Review as needed [Predictive Model Building](https://stat-ata-asu.github.io/PredictiveModelBuilding/)
  
* * * 

## Week 12: (Apr 8 & 10) {-}

+ Read the chapter [Model Tuning and the Dangers of Overfitting](https://www.tmwr.org/tuning)
    
+ Read Chapters 5-6 in [Tree based Models in R](https://mathr.appstate.edu/connect/content/417890f7-c144-44ec-86b5-6437891c8c2d)

+ [Start Chapters 3 and 4 in _Machine Learning with Tree Based Models in R_ on DataCamp](https://app.datacamp.com/groups/stt3850-s2025/assignments)---Due Apr 14 NLT 5:00 PM 

+ Start reproduction of [_Machine Learning with Tree Based Models in R_]() - Due Apr 21 NLT 5:00 PM

+ Review as needed [Train and Test](../rmarkdown/TrainAndTestPartitions.html)
    
+ Review as needed [Regression Trees](../rmarkdown/RegressionTrees.html)
    
+ Review as needed [Predictive Model Building](https://stat-ata-asu.github.io/PredictiveModelBuilding/)


    
* * *

## Week 13: (Apr 15 & 17) {-}

+ Read the chapter [Grid Search](https://www.tmwr.org/grid-search)

+ Work on reproduction of [_Machine Learning with Tree Based Models in R_](https://classroom.github.com/a/n-LskGWs) - Due Apr 21 NLT 5:00 PM
    
* * *

## Week 14: (Apr 22 & 24) {-}

+ Finish reproduction of [_Machine Learning with Tree Based Models in R_](https://classroom.github.com/a/n-LskGWs) - Due Apr 21 NLT 5:00 PM
  
+ Pick data for group project #2 from `modeldata` package.  Data must have at least 8 variables and 1,000 or more rows.  Accept group project [here]().  Group presentations will be May 6 during the final exam period.    
  
* * * 

## Week 15: (Apr 29) {-}

+ Work on group presentation.

* * *


## Final Exam Period (May 6---11 am - 1:30 pm) {-}

+ Final Group Presentations
  
* * *


### Final Exam {-}

```{block, FINAL, type='rmdnote'}
*  [University Exam Schedule](https://registrar.appstate.edu/sites/default/files/app_state_spring_2024_exam_schedule_final.pdf)
```

________________

<center> Last Updated on: `r format(Sys.time(), "%b %d, %Y at %X")` </center>

________________
