---
title: "STT 3860 - Introduction to Statistical Modeling - Tentative Course Schedule - Spring 2023"
author: ""
date: ""
output: 
  bookdown::html_document2: 
    highlight: textmate
    theme: yeti
    css: "../css/style.css"
---

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>

* * *

### General Notes: {-}

```{block, note-text, type='rmdnote'}
Please bring a notebook and pencil to every class.  
```

* * *

* Week 1 (Jan 17, 19): Review concepts and ideas from `rmarkdown`, `knitr`, `bookdown`, Git, and GitHub
    
    + [R Markdown](http://rmarkdown.rstudio.com/)
    
    + [knitr](https://yihui.name/knitr/)
    
    + [bookdown: Authoring Books and Technical Documents with R Markdown](https://bookdown.org/yihui/bookdown/)
    
    + [Happy Git and GitHub for the useR](http://happygitwithr.com/)

    + Send an email to arnholtat@appstate.edu with a Subject line of **STT3860 - GitHub Username**, and tell me in the body of your email your first name, last name, and your GitHub username.  
    
    + Make sure RStudio is set up to communicate with Git by following the directions in [HappyGitWithR](https://happygitwithr.com/hello-git.html) for introducing yourself to Git.---[VIDEO of the setup process](https://drive.google.com/file/d/1G9G8IeYu9QetYB1nxMmAFLgRtw5YC-c8/view?usp=sharing)

    + Set cache your credentials and set up a personal access token (PAT) by following the directions in [HappyGitWithR](https://happygitwithr.com/credential-caching.html). 
    
    + [Set Global Options](https://stat-ata-asu.github.io/STT5812CourseRepo/Rmarkdown/GlobalOptions.html)
    
    + [Miscellaneous Tips](https://alanarnholt.github.io/GeneralStatistics/rmarkdown/MiscRmarkdown.html)
    
```{block, week1optional, type='rmdoptional'}   
Optional Resources:

* [DataCamp: Communicating with Data in the Tidyverse](https://www.datacamp.com/courses/communicating-with-data-in-the-tidyverse)

* [Data Science with R](https://stat-ata-asu.github.io/R_DS_BD2020/)

* [DataCamp: Introduction to Git for Data Science](https://www.datacamp.com/courses/introduction-to-git-for-data-science)

* [Reading in Data](https://alanarnholt.github.io/STT3850/Handouts/WorkingWithDataRevised.html)
``` 


* * *

* Week 2 (Jan 24, 26)

  + Read Chapter 2 of [Correlation and Regression](https://mathr.math.appstate.edu/connect/content/71419336-3676-4c19-9077-f018b948229d)
  
  + [Complete Chapter 1 in Dealing with Missing Data in R on DataCamp - Why care about missing data? ](https://app.datacamp.com/groups/stt3860-sp23/assignments)---Due Jan 24 NLT 5:00 PM 
  
  + Complete and turn in a hard copy of your summary of "Why care about missing data?" using RMarkdown---Due Jan 26 NLT 5:00 PM  
  
  + Misc Regression [topics](https://alanarnholt.github.io/STT3850/Rmarkdown/MiscRegression.html)

* * * 

* Week 3 (Jan 31, Feb 2)
   
   + Read Chapter 3 of [Correlation and Regression](https://mathr.math.appstate.edu/connect/content/71419336-3676-4c19-9077-f018b948229d)
  
  + [Complete Chapter 2 in Dealing with Missing Data in R on DataCamp - Wrangling and tidying up missing values](https://app.datacamp.com/groups/stt3860-sp23/assignments)---Due Jan 31 NLT 5:00 PM
  
  + Complete and turn in a hard copy of your summary of "Wrangling and tidying up missing values" using RMarkdown---Due Feb 2 NLT 5:00 PM       
    
* * *

* Week 4 (Feb 7, 9)

     + Read Chapter 4 of [Correlation and Regression](https://mathr.math.appstate.edu/connect/content/71419336-3676-4c19-9077-f018b948229d)
    
    + [Complete Chapter 3 in Dealing with Missing Data in R on DataCamp - Testing missing relationships](https://app.datacamp.com/groups/stt3860-sp23/assignments)---Due Feb 7 NLT 5:00 PM
  
  + Complete and turn in a hard copy of your summary of "Testing missing relationships" using RMarkdown---Due Feb 9 NLT 5:00 PM   
    
* * *

* Week 5 (Feb 14, 16)
    
     + Read Chapter 5 of [Correlation and Regression](https://mathr.math.appstate.edu/connect/content/71419336-3676-4c19-9077-f018b948229d)
    
    + [Complete Chapter 4 in Dealing with Missing Data in R on DataCamp - Connecting the dots imputation](https://app.datacamp.com/groups/stt3860-sp23/assignments)---Due Feb 14 NLT 5:00 PM
  
  + Complete and turn in a hard copy of your summary of "Connecting the dots imputation" using RMarkdown---Due Feb 16 NLT 5:00 PM
  
   + [START LAB1: Questioning and Cleaning the bodyfat data Lab---Due Feb 23 NLT 5:00 PM](https://classroom.github.com/a/B5A12MYZ) 
   
   + In class review [this document.](https://alanarnholt.github.io/STT3850/Handouts/RegHandout.html)

* * *

* Week 6 (Feb 21, 23)

    + Read Chapter 6 of [Correlation and Regression](https://mathr.math.appstate.edu/connect/content/71419336-3676-4c19-9077-f018b948229d)
   
   + [LAB1: Questioning and Cleaning the bodyfat data Lab---Due Feb 23 NLT 5:00 PM](https://classroom.github.com/a/B5A12MYZ) 

* * *

* Week 7 (Feb 28, Mar 2)

    + Read [Appendix E.](https://mdsr-book.github.io/mdsr2e/ch-regression.html#simple-linear-regression)
    
    + [Complete Chapters  1 and 2 in Modeling with Data in the Tidyverse on DataCamp - Introduction to Modeling & Modeling with Basic Regression](https://app.datacamp.com/groups/stt3860-sp23/assignments)---Due Feb 28 NLT 5:00 PM
  
    + Complete and turn in a hard copy of your summary of "Introduction to Modeling & Modeling with Basic Regression" using RMarkdown---Due Mar 2 NLT 5:00 PM 
    
    

* * *

* Week 8 (Mar 7, 9)

     + Read [Appendix E.](https://mdsr-book.github.io/mdsr2e/ch-regression.html#simple-linear-regression)
    
    + [Complete Chapters  3 and 4 in Modeling with Data in the Tidyverse on DataCamp - Modeling with Multiple Regression & Model Assessment and Selection](https://app.datacamp.com/groups/stt3860-sp23/assignments)---Due Mar 7 NLT 5:00 PM 
  
    + Complete and turn in a hard copy of your summary of "Modeling with Multiple Regression & Model Assessment and Selection" using RMarkdown---Due Mar 9 NLT 5:00 PM 
    
    
* * *   

* March 13-17 __Spring Break__

* * *

* Week 9 (Mar 21, 23)

    + [Complete Chapters 1-5 in Machine Learning with `caret` in R on DataCamp](https://app.datacamp.com/groups/stt3860-sp23/assignments)---Due Mar 22 NLT 5:00 PM
  
    + Complete and turn in a hard copy of your summary of "Machine Learning with `caret` in R" using RMarkdown.  Due Mar 23 NLT 5:00 PM 
    
     + [START LAB2: Linear models with the bodyfat data Lab---Due Mar 30 NLT 5:00 PM](https://classroom.github.com/a/ffbLB8cD) 

* * *

* Week 10 (Mar 28, 30)

    + Read [Predictive Model Building](https://stat-ata-asu.github.io/PredictiveModelBuilding/)
    
    + Read [Multiple and Logistic Regression](https://mathr.math.appstate.edu/connect/content/493bca23-1118-4e56-9e3f-f35585deb611)
    
    + [LAB2: Linear models with the bodyfat data Lab---Due Mar 30 NLT 5:00 PM](https://classroom.github.com/a/ffbLB8cD) 

* * *


* Week 11 (Apr 4, 6)

    + Extra Credit---[Combine previous Rmarkdown assignments into Bookdown document](put classroom github link here)
    
    + Read [Tree based Models in R](https://mathr.math.appstate.edu/connect/content/4ae25dab-1ef6-4902-b29b-00c82b9c8fff)
    
    + Review as needed [Train and Test](../rmarkdown/TrainAndTestPartitions.html)
    
    + Review as needed [Regression Trees](../rmarkdown/RegressionTrees.html)
    
    + Review as needed [Predictive Model Building](https://stat-ata-asu.github.io/PredictiveModelBuilding/)
    
     + [START LAB3: Non-linear models with the bodyfat data Lab---Due Apr 13 NLT 5:00 PM](https://classroom.github.com/a/PZf8LJ_-) 
    

* * * 

* Week 12 (Apr 11, 13)

    + Read [Tree based Models in R](https://mathr.math.appstate.edu/connect/content/4ae25dab-1ef6-4902-b29b-00c82b9c8fff)
    
    + Review as needed [Train and Test](../rmarkdown/TrainAndTestPartitions.html)
    
    + Review as needed [Regression Trees](../rmarkdown/RegressionTrees.html)
    
    + Review as needed [Predictive Model Building](https://stat-ata-asu.github.io/PredictiveModelBuilding/)
    
    + [LAB3: Non-linear models with the bodyfat data Lab---Due Apr 13 NLT 5:00 PM](https://classroom.github.com/a/PZf8LJ_-) 
    
* * *

* Week 13 (Apr 18, 20)

    + Pick a data set from the [UCI machine learning repository](https://archive.ics.uci.edu/ml/index.php)

    + Clean chosen data and make models
    
* * *

* Week 14 (Apr 25, 27)

    + Pick a data set from the [UCI machine learning repository](https://archive.ics.uci.edu/ml/index.php)

    + Clean chosen data and make models
  
    
  
* * * 

* Week 15 (May 2)

    + Prepare **group** presentation.  Accept materials [here](https://classroom.github.com/a/2mnclwn7) 

* * *


* Final Exam Period (May 11---11 am -1:30 pm)

  + Group Presentations
  
* * *


### Final Exam {-}

```{block, FINAL, type='rmdnote'}
*  [University Exam Schedule](https://registrar.appstate.edu/sites/default/files/app_state_spring_2023_exam_schedule_final.pdf)
```

________________

<center> Last Updated on: `r format(Sys.time(), "%b %d, %Y at %X")` </center>

________________
